name: xclusiv
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.1.0
  cloud_firestore: ^2.0.0
  firebase_auth: ^1.2.0
  google_sign_in: ^5.2.4
  flutter_svg: ^0.22.0
  cached_network_image: ^3.0.0
  image_picker: ^0.7.4
  image: ^3.1.3
  uuid: ^3.0.4
  firebase_storage: ^8.0.5
  geolocator: 7.7.0
  geocoding: ^2.0.1
  animator: 3.0.0
  flutter_animator: ^3.1.1
  timeago: 3.0.2
  transformer_page_view: ^0.1.6
  carousel_slider: ^3.0.0
  sliding_up_panel: ^2.0.0+1
  provider: ^5.0.0
  #firebase_messaging: ^9.1.3
  #firebase_functions_interop: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - assets/images/google_signin_button.png
  - assets/images/upload.svg
  - assets/images/search.svg
  - assets/images/activity_feed.svg
  - assets/images/no_content.svg
  - assets/images/ew13.jpeg
  - assets/images/in20.jpeg
  - assets/images/arb7.jpg
  - assets/images/africa7.JPG
  - assets/images/pl15.jpg
  - assets/images/cr12.jpeg
  - assets/images/cnc17.jpeg
  - assets/images/b14.jpeg
  - assets/images/gl15.jpeg
  - assets/images/f1.jpeg
  - assets/images/user1.jpeg
  - assets/images/user2.jpeg
  - assets/images/user3.jpeg
  - assets/images/user4.jpeg
  - assets/images/photo1.jpg
  - assets/images/photo2.jpg
  - assets/images/photo3.jpg
  - assets/images/sales1.jpg
  - assets/images/men1.jpg
  - assets/images/women1.jpg
  - assets/images/kids1.jpg
  - assets/images/services1.jpg
  - assets/images/brands1.jpg
  - assets/images/ms.jpg
  - assets/images/mc.jpg
  - assets/images/ma.jpg
  - assets/images/mf.jpg
  - assets/images/ib3.png
  - assets/images/ib2.png
  - assets/images/product1.jpg
  - assets/images/product2.jpg
  - assets/images/product3.jpg
  - assets/images/product4.jpg
  - assets/icons/Heart Icon.svg
  - assets/icons/Heart Icon_2.svg
  - assets/icons/User Icon.svg
  - assets/icons/Settings.svg
  - assets/icons/Question mark.svg
  - assets/icons/User Icon.svg
  - assets/icons/Parcel.svg
  - assets/images/newin.jpg


  fonts:
  - family: Signatra
    fonts:
      - asset: assets/fonts/Signatra.ttf
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
